/*
- Viz: https://datastudio.google.com/u/2/reporting/28d75b3f-3853-4fe0-8440-279eaa6c0e66/page/FajmB
- Data: 
- Function: 
- Table:
- File: 
- Path: 
- Document/Presentation/Dashboard: 
- Email thread: 
- Notes (if any): 
*/

-- query in backend
select
	s.min_date ,
	s.total_1st_day_active_user,
	s.total_registered_user,
	case when s.total_registered_user>0 then  s.total_1st_day_active_user/s.total_registered_user::float else 0 end as first_use_pct,
	d.first_day_active as first_dau_reg_pct,
	tbl_1.verified_unverified_1st_dau
from 
	tallykhata.first_activity_vs_reg_ratio as s 
	inner join 
	tallykhata.used_on_registration_day_dashboard as d on s.min_date = d.registration_date
	inner join 
	(select 
		registration_date	
		,total_user	
		,total_active_user	
		,first_day_active	
		,coalesce(number_of_unverified_user,0) as number_of_unverified_user
		,coalesce(i.daily_user_installs,0) as number_of_new_download
		,coalesce((total_active_user+coalesce(number_of_unverified_user,0))/nullif(coalesce(i.daily_user_installs,0)::float,0),0) as verified_unverified_1st_dau
	from 
		tallykhata.used_on_registration_day_dashboard as vd 
		left join 
		tallykhata.unverified_1st_dau as ud on vd.registration_date  = ud.create_date
		left join 
		public.playstore_installs as i on vd.registration_date  = i.report_date
	) as tbl_1 on d.registration_date = tbl_1.registration_date
where 
	s.min_date >='2020-07-01'
	and s.min_date <current_date;

-- problematic col: first_use_pct
-- problematic root col: total_1st_day_active_user
-- problmatic problematic root table: tallykhata.first_activity_vs_reg_ratio
-- problematic root table generated by: tallykhata.fn_first_activity_vs_reg_count_final()
-- incorrect data found in table: tallykhata.user_wise_min_txn_date

-- temporary fix
delete from tallykhata.first_activity_vs_reg_ratio where min_date>=current_date-30;
insert into tallykhata.first_activity_vs_reg_ratio
select 
	tbl_1.min_date,
	sum(tbl_1.total_1st_day_active_user) as total_1st_day_active_user,
	sum(tbl_1.total_registered_user) as total_registered_user
from 
	(select created_datetime min_date, count(distinct mobile_no) as total_1st_day_active_user, 0 as total_registered_user
	from tallykhata.tallykhata_transacting_user_date_sequence_final
	where 
		date_sequence=1
		and created_datetime>=current_date-30 and created_datetime<current_date
	group by 1
  
  	union all 
  
  	select 
  		m.created_at::date,
  		0 as total_1st_day_active_user,
  		count(distinct m.mobile_number) as total_registered_user
  	from public.register_usermobile as m  where m.created_at::date>=current_date-30
  	group by m.created_at::date 
  	) as tbl_1
group by min_date; 

-- expected to function well after table got a temporary fix, since tallykhata.user_wise_min_txn_date renews past 1-day data daily 
